#!/bin/sh -
#
# build script for 1.2
#
# If it's given a buildname it creates a subdirectory and places a build in it,
# otherwise it just creates the docs and class files.
#

JDK12PATH=/opt/jdk1.2.2   # JDK 1.2 location

base=$1
version=`echo $base | sed -e "s/\([0-9]\)\([0-9a-z]*\)/\1.\2/"`

WINDOWTITLE="Bouncy Castle Cryptography $version API Specification"
HEADER="<b>Bouncy Castle Cryptography $version</b>"
DOCTITLE="Bouncy Castle $version API Specification"

jdk12src=build/jdk1.2
artifacts=build/artifacts/jdk1.2

mkdir -p $jdk12src

((cd jce/src/main/java && tar cf - *) | (cd $jdk12src && tar xf -))
((cd core/src/main/java && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd core/src/main/jdk1.4 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd core/src/main/jdk1.3 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd core/src/main/jdk1.2 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd core/src/test/java && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd core/src/test/jdk1.4 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd core/src/test/jdk1.3 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd core/src/test/jdk1.2 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd core/src/main/javadoc && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd prov/src/main/java && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd prov/src/main/javadoc && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd prov/src/test/java && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd prov/src/main/jdk1.4 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd prov/src/test/jdk1.4 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd prov/src/main/jdk1.3 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd prov/src/test/jdk1.3 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd prov/src/main/jdk1.2 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pkix/src/main/java && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pkix/src/main/javadoc && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pkix/src/test/java && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pkix/src/main/jdk1.4 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pkix/src/test/jdk1.4 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pkix/src/main/jdk1.3 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pkix/src/test/jdk1.3 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pkix/src/main/jdk1.2 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pg/src/main/java && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pg/src/main/jdk1.4 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pg/src/main/jdk1.3 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pg/src/test/java && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pg/src/test/jdk1.4 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pg/src/test/jdk1.3 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pg/src/test/jdk1.2 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd util/src/main/java && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd util/src/main/javadoc && tar cf - * ) | (cd $jdk12src && tar xf -))

find $jdk12src -name "*.java" -exec scripts/trim.sh \{\} \;
find $jdk12src -name "*.java" -exec scripts/usejcecert.sh \{\} \;

(
    cd $jdk12src

    rm -rf com/distrimind/bouncycastle/math/ec/rfc8032/test
    rm -rf com/distrimind/bouncycastle/crypto/test/ntru
    rm -rf com/distrimind/bouncycastle/pqc/math/ntru
    rm -rf com/distrimind/bouncycastle/pqc/crypto/ntru
    rm -rf com/distrimind/bouncycastle/pqc/crypto/*/NTRU*
    rm -rf com/distrimind/bouncycastle/pqc/crypto/xmss
    rm -rf com/distrimind/bouncycastle/pqc/crypto/lms
    rm -rf com/distrimind/bouncycastle/pqc/jcajce/provider/xmss
    rm -rf com/distrimind/bouncycastle/pqc/jcajce/provider/XMSS*
    rm -rf com/distrimind/bouncycastle/pqc/jcajce/provider/LMS*
    rm -rf com/distrimind/bouncycastle/pqc/jcajce/provider/lms
    rm -rf com/distrimind/bouncycastle/pqc/crypto/*/XMSS*
    rm -rf com/distrimind/bouncycastle/pqc/crypto/*/LMS*
    rm -rf com/distrimind/bouncycastle/pqc/crypto/*/HSS*
    rm -rf com/distrimind/bouncycastle/pqc/crypto/*/EncryptionKey*
    rm -rf com/distrimind/bouncycastle/pqc/crypto/*/BitStringT*
    rm -rf com/distrimind/bouncycastle/pqc/crypto/*/CMCEVectorTest*
    rm -rf com/distrimind/bouncycastle/pqc/crypto/*/FrodoVectorTest*
    rm -rf com/distrimind/bouncycastle/pqc/crypto/*/SABERVectorTest*
    rm com/distrimind/bouncycastle/pqc/jcajce/spec/LMS*
    rm -rf com/distrimind/bouncycastle/crypto/*/test
    rm -rf com/distrimind/bouncycastle/crypto/*/IndexGenerator*
    rm -rf com/distrimind/bouncycastle/crypto/test/SimpleTestTest.java
    rm -rf com/distrimind/bouncycastle/util/utiltest
    rm -rf com/distrimind/bouncycastle/mail
    rm -rf com/distrimind/bouncycastle/mime
    rm com/distrimind/bouncycastle/pkix/test/CheckerTest.java
    rm com/distrimind/bouncycastle/pkix/jcajce/Revocation*.java
    rm com/distrimind/bouncycastle/pkix/jcajce/X509RevocationChecker.java
    rm com/distrimind/bouncycastle/pkix/jcajce/RFC3280*.java
    rm com/distrimind/bouncycastle/cms/jcajce/JceKeyTransAuthEnvelopedRecipient.java
    rm com/distrimind/bouncycastle/cms/jcajce/JceAADStream.java
    rm com/distrimind/bouncycastle/jcajce/provider/keystore/util/ParameterUtil.java
    rm -rf com/distrimind/bouncycastle/jce/provider/test/SimpleTestTest.java
    rm -rf com/distrimind/bouncycastle/oer
    rm -rf com/distrimind/bouncycastle/i18n/test
    rm -rf com/distrimind/bouncycastle/i18n/filter/test
    rm -rf com/distrimind/bouncycastle/math/ec/test
    rm -rf com/distrimind/bouncycastle/crypto/tls/test
    rm -rf com/distrimind/bouncycastle/crypto/test/GCMReorderTest.java
    rm -rf com/distrimind/bouncycastle/crypto/test/NISTECCTest.java
    rm -rf com/distrimind/bouncycastle/jce/ECPointUtil.java
    rm -rf com/distrimind/bouncycastle/jce/X509LDAP*.java
    rm -rf com/distrimind/bouncycastle/jce/provider/X509LDAP*.java
    rm -rf com/distrimind/bouncycastle/jce/provider/JCEEC5*.java
    rm -rf com/distrimind/bouncycastle/jce/provider/EC5*.java
    rm -rf com/distrimind/bouncycastle/jce/provider/JCEEC*.java
    rm -rf com/distrimind/bouncycastle/jcajce/provider/asymmetric/ec/EC5Util.java
    rm -rf com/distrimind/bouncycastle/jcajce/provider/asymmetric/ecgost12
    rm -rf com/distrimind/bouncycastle/jcajce/provider/test
    rm -rf com/distrimind/bouncycastle/math/ec/rfc7748/test
    rm com/distrimind/bouncycastle/jcajce/BCFKSStoreParameter.java
    rm -rf com/distrimind/bouncycastle/jce/provider/asymmetric/ec/EC5*.java
    rm -rf com/distrimind/bouncycastle/jce/provider/test/ECDSA5Test.java
    rm -rf com/distrimind/bouncycastle/jce/provider/test/CRL5Test.java
    rm -rf com/distrimind/bouncycastle/jce/provider/test/X509LDAP*.java
    rm -rf com/distrimind/bouncycastle/jce/provider/test/MQVTest*.java
    rm -rf com/distrimind/bouncycastle/jce/provider/test/AlgorithmParametersTest.java
    rm -rf com/distrimind/bouncycastle/jce/provider/test/GOST3410KeyPairTest.java
    rm -rf com/distrimind/bouncycastle/jce/provider/test/ChaCha20Poly1305Test.java
    rm -rf com/distrimind/bouncycastle/jce/spec/ECNamedCurveSpec.java
    rm -rf com/distrimind/bouncycastle/util/encoders/test/*.java
    rm -rf com/distrimind/bouncycastle/x509/PKIXCertPathReviewer.java
    rm -rf com/distrimind/bouncycastle/x509/CertPathReviewerException.java
    rm -rf com/distrimind/bouncycastle/x509/util/LDAPStoreHelper.java
    rm -rf com/distrimind/bouncycastle/jce/provider/X509StoreLDAPAttrCerts.java
    rm -rf com/distrimind/bouncycastle/jce/provider/X509StoreLDAPCertPairs.java
    rm -rf com/distrimind/bouncycastle/jce/provider/X509StoreLDAPCerts.java
    rm -rf com/distrimind/bouncycastle/jce/provider/X509StoreLDAPCRLs.java
    rm -rf com/distrimind/bouncycastle/jce/provider/PKIXAttrCert*.java
    rm -rf com/distrimind/bouncycastle/jce/provider/PKIXNameConstraints*.java
    rm -rf com/distrimind/bouncycastle/jce/provider/test/PKIXNameConstraintsTest.java
    rm -rf com/distrimind/bouncycastle/jce/provider/test/nist
    rm -rf com/distrimind/bouncycastle/jce/provider/test/rsa3
    rm -rf com/distrimind/bouncycastle/jce/provider/test/DSTU4145Test.java
    rm -rf com/distrimind/bouncycastle/jce/provider/test/JceTestUtil.java
    rm -f com/distrimind/bouncycastle/jce/provider/PKIXCertPathValidatorSpi_8.java
    rm -f com/distrimind/bouncycastle/jce/provider/PKIXCertPathBuilderSpi_8.java
    rm -f com/distrimind/bouncycastle/jce/provider/WrappedRevocationChecker.java
    rm -f com/distrimind/bouncycastle/jce/provider/ProvRevocationChecker.java
    rm -f com/distrimind/bouncycastle/jce/provider/OcspCache.java
    rm -f com/distrimind/bouncycastle/jce/provider/ProvOcspRevocationChecker.java
    rm -rf com/distrimind/bouncycastle/x509/PKIXAttrCert*.java
    rm -rf com/distrimind/bouncycastle/jce/provider/RFC3281*.java
    rm -rf com/distrimind/bouncycastle/jcajce/PKCS12StoreParameter.java
    rm com/distrimind/bouncycastle/jce/provider/test/DetDSATest.java
    rm com/distrimind/bouncycastle/jce/provider/test/AEADTest.java
    rm -rf com/distrimind/bouncycastle/jce/provider/JDKPKCS12StoreParameter.java
    rm -rf com/distrimind/bouncycastle/jcajce/BC*LoadStore*.java
    rm -rf com/distrimind/bouncycastle/jcajce/spec/DSTU4145*.java
    rm -rf com/distrimind/bouncycastle/jcajce/provider/config/PKCS12StoreParameter.java
    rm -rf com/distrimind/bouncycastle/jcajce/provider/test/PrivateConstructorTest.java
    rm -rf com/distrimind/bouncycastle/jcajce/provider/test/ECAlgorithmParametersTest.java
    rm -rf com/distrimind/bouncycastle/jcajce/provider/test/RandomTest.java
    rm -rf com/distrimind/bouncycastle/jce/provider/test/ECEncodingTest.java
    rm com/distrimind/bouncycastle/asn1/test/GetInstanceTest.java
    rm com/distrimind/bouncycastle/asn1/test/ASN1SequenceParserTest.java
    rm com/distrimind/bouncycastle/asn1/test/OctetStringTest.java
    rm com/distrimind/bouncycastle/asn1/test/ParseTest.java
    rm com/distrimind/bouncycastle/pkix/test/RevocationTest.java
    rm com/distrimind/bouncycastle/pkix/test/TestUtil.java
    rm com/distrimind/bouncycastle/cert/ocsp/test/PKIXRevocationTest.java
    rm -r com/distrimind/bouncycastle/crypto/test/BigSkippingCipherTest.java
    rm -rf com/distrimind/bouncycastle/openssl/test
    rm -rf com/distrimind/bouncycastle/jcajce/provider/asymmetric/dstu
    rm -rf com/distrimind/bouncycastle/jcajce/provider/asymmetric/DSTU*.java
    rm -rf com/distrimind/bouncycastle/jcajce/provider/asymmetric/util/EC5*.java
    rm com/distrimind/bouncycastle/asn1/test/EnumeratedTest.java
    rm -rf com/distrimind/bouncycastle/pqc/crypto/test/QT*.java
    rm -rf com/distrimind/bouncycastle/pqc/crypto/test/SphincsPlusTest.java
    rm -rf com/distrimind/bouncycastle/pqc/crypto/qtesla/QT*Tests.java
    rm -rf com/distrimind/bouncycastle/pqc/jcajce/provider/test
    rm -r com/distrimind/bouncycastle/crypto/test/speedy
    rm -r com/distrimind/bouncycastle/crypto/test/cavp
    rm -r com/distrimind/bouncycastle/crypto/test/KDFFeedbackGeneratorTest.java
    rm -r com/distrimind/bouncycastle/crypto/test/KDFDoublePipelineIteratorGeneratorTest.java
    rm -r com/distrimind/bouncycastle/crypto/test/KDFCounterGeneratorTest.java
    rm -r com/distrimind/bouncycastle/math/test/PrimesTest.java
    rm -r com/distrimind/bouncycastle/math/raw/test/InterleaveTest.java
    rm -rf com/distrimind/bouncycastle/cert/jcajce/JcaAttributeCertificateIssuer.java
    rm -rf com/distrimind/bouncycastle/cert/test/ConverterTest*
    rm -rf com/distrimind/bouncycastle/cert/test/CertPathLoopTest.java
    rm -rf com/distrimind/bouncycastle/cert/test/Bc*
    rm -rf com/distrimind/bouncycastle/tsp/GenTimeAccuracyUnit*
    rm -rf com/distrimind/bouncycastle/tsp/TimeStampTokenInfoUnit*
    rm  com/distrimind/bouncycastle/openpgp/test/BcPGPEd25519JcaKeyPairConversionTest.java
    rm  com/distrimind/bouncycastle/openpgp/test/ArmoredOutputStreamUTF8Test.java

    sh ../../scripts/jdk1.2ed.sh

    find . -name AllTests.java -exec rm {} \;
    ( find . -name CVS -exec rm -r {} \; ) > /dev/null 2>&1 
)

mkdir -p $artifacts

if test "$base" != ""  -a ! -d $artifacts/lcrypto-jdk12-$base
then
    echo "making lightweight release"

    mkdir $artifacts/lcrypto-jdk12-$base
    mkdir $artifacts/lcrypto-jdk12-$base/src

    tar cf - index.html LICENSE.html CONTRIBUTORS.html docs | (cd $artifacts/lcrypto-jdk12-$base && tar xf -)
    ((cd $jdk12src && tar cf - java com/distrimind/bouncycastle/LICENSE.java \
    com/distrimind/bouncycastle/math com/distrimind/bouncycastle/internal com/distrimind/bouncycastle/crypto com/distrimind/bouncycastle/util com/distrimind/bouncycastle/asn1 com/distrimind/bouncycastle/pqc/math com/distrimind/bouncycastle/pqc/crypto com/distrimind/bouncycastle/pqc/asn1  ) | (cd $artifacts/lcrypto-jdk12-$base/src && tar xf -))
    (
        cd $artifacts/lcrypto-jdk12-$base;

        mkdir classes; mkdir javadoc;

        (2>&1 javadoc -windowtitle "$WINDOWTITLE" -doctitle "$DOCTITLE" \
            -header "$HEADER" \
            -group "Lightweight Crypto Packages" "com.distrimind.bouncycastle.crypto*" \
            -group "ASN.1 Support Packages" "com.distrimind.bouncycastle.asn1*" \
            -group "Math Support Packages" "com.distrimind.bouncycastle.math*" \
            -group "Utility Packages" "com.distrimind.bouncycastle.util*" \
            -classpath classes \
            -d javadoc -sourcepath src \
            com.distrimind.bouncycastle.asn1 \
            com.distrimind.bouncycastle.asn1.cmp \
            com.distrimind.bouncycastle.asn1.cms \
            com.distrimind.bouncycastle.asn1.cryptopro \
            com.distrimind.bouncycastle.asn1.esf \
            com.distrimind.bouncycastle.asn1.ess \
            com.distrimind.bouncycastle.asn1.gnu \
            com.distrimind.bouncycastle.asn1.iana \
            com.distrimind.bouncycastle.asn1.icao \
            com.distrimind.bouncycastle.asn1.misc \
            com.distrimind.bouncycastle.asn1.mozilla \
            com.distrimind.bouncycastle.asn1.nist \
            com.distrimind.bouncycastle.asn1.ocsp \
            com.distrimind.bouncycastle.asn1.oiw \
            com.distrimind.bouncycastle.asn1.pkcs \
            com.distrimind.bouncycastle.asn1.sec \
            com.distrimind.bouncycastle.asn1.smime \
            com.distrimind.bouncycastle.asn1.teletrust \
            com.distrimind.bouncycastle.asn1.test \
            com.distrimind.bouncycastle.asn1.tsp \
            com.distrimind.bouncycastle.asn1.util \
            com.distrimind.bouncycastle.asn1.x509 \
            com.distrimind.bouncycastle.asn1.x9 \
            com.distrimind.bouncycastle.math.ec \
            com.distrimind.bouncycastle.crypto \
            com.distrimind.bouncycastle.crypto.agreement \
            com.distrimind.bouncycastle.crypto.commitments \
            com.distrimind.bouncycastle.crypto.digests \
            com.distrimind.bouncycastle.crypto.encodings \
            com.distrimind.bouncycastle.crypto.ec \
            com.distrimind.bouncycastle.crypto.engines \
            com.distrimind.bouncycastle.crypto.generators \
            com.distrimind.bouncycastle.crypto.io \
            com.distrimind.bouncycastle.crypto.kems \
            com.distrimind.bouncycastle.crypto.macs \
            com.distrimind.bouncycastle.crypto.modes \
            com.distrimind.bouncycastle.crypto.paddings \
            com.distrimind.bouncycastle.crypto.params \
            com.distrimind.bouncycastle.crypto.signers \
            com.distrimind.bouncycastle.crypto.test \
            com.distrimind.bouncycastle.crypto.examples \
            com.distrimind.bouncycastle.crypto.tls \
            com.distrimind.bouncycastle.util.encoders \
            com.distrimind.bouncycastle.util.test) > /dev/null \

        PATH=$JDK12PATH/bin:$PATH
        export PATH

        echo "compiling"

        (cd src/com/distrimind/bouncycastle; javac -d ../../../classes -classpath ../../../classes:../../../src *.java */*.java internal/*/*/*.java  )
        (cd src/com/distrimind/bouncycastle; javac -d ../../../classes -classpath ../../../classes:../../../src a*/*/*.java )
        (cd src/com/distrimind/bouncycastle; javac -d ../../../classes -classpath ../../../classes:../../../src [bcdefghijklmnopqrstuv]*/*/*.java )

        echo "lightweight regression test"

        cp ../../../../core/src/test/resources/com/distrimind/bouncycastle/crypto/test/*.txt src/com/distrimind/bouncycastle/crypto/test
        cp ../../../../core/src/test/resources/com/distrimind/bouncycastle/crypto/test/*.txt classes/com/distrimind/bouncycastle/crypto/test
        cp ../../../../core/src/test/resources/com/distrimind/bouncycastle/asn1/test/*.data classes/com/distrimind/bouncycastle/asn1/test

        java -classpath classes -Dbc.test.data.home=../core/src/test/data com.distrimind.bouncycastle.crypto.test.RegressionTest
        java -classpath classes com.distrimind.bouncycastle.asn1.test.RegressionTest
    )
    (2>&1 find $artifacts/lcrypto-jdk12-$base -name CVS -exec rm -rf \{\} \; ) > /dev/null
fi

if  test "$base" != "" -a ! -d $artifacts/jce-jdk12-$base
then
    echo "making JCE release"

    mkdir $artifacts/jce-jdk12-$base
    mkdir $artifacts/jce-jdk12-$base/src
    tar cf - index.html LICENSE.html CONTRIBUTORS.html docs | (cd $artifacts/jce-jdk12-$base; tar xf -)
    ((cd $jdk12src && tar cf - java javax com/distrimind/bouncycastle/LICENSE.java com/distrimind/bouncycastle/crypto com/distrimind/bouncycastle/internal com/distrimind/bouncycastle/math com/distrimind/bouncycastle/pqc com/distrimind/bouncycastle/asn1 com/distrimind/bouncycastle/jcajce com/distrimind/bouncycastle/util com/distrimind/bouncycastle/jce com/distrimind/bouncycastle/x509 ) | (cd $artifacts/jce-jdk12-$base/src && tar xf -))

    (
    cd $artifacts/jce-jdk12-$base; mkdir classes; mkdir javadoc;

    (2>&1 javadoc -windowtitle "$WINDOWTITLE" -doctitle "$DOCTITLE" \
        -header "$HEADER" \
        -group "Cleanroom JCE" "javax.crypto*" \
        -group "JCE Utility and Extension Packages" "com.distrimind.bouncycastle.jce*" \
        -group "OCSP and OpenSSL PEM Support Packages" "com.distrimind.bouncycastle.ocsp*:com.distrimind.bouncycastle.openssl*" \
        -group "ASN.1 Support Packages" "com.distrimind.bouncycastle.asn1*" \
        -group "Lightweight Crypto Packages" "com.distrimind.bouncycastle.crypto*" \
        -group "Utility Packages" "com.distrimind.bouncycastle.util*:com.distrimind.bouncycastle.math*" \
        -group "JCE Provider and Test Classes" "com.distrimind.bouncycastle.jce.provider*" \
        -classpath classes \
        -d docs -sourcepath src \
        java.security.spec \
        javax.crypto  \
        javax.crypto.interfaces \
        javax.crypto.spec \
        com.distrimind.bouncycastle.asn1 \
        com.distrimind.bouncycastle.asn1.cmp \
        com.distrimind.bouncycastle.asn1.cms \
        com.distrimind.bouncycastle.asn1.cryptopro \
        com.distrimind.bouncycastle.asn1.esf \
        com.distrimind.bouncycastle.asn1.ess \
        com.distrimind.bouncycastle.asn1.gnu \
        com.distrimind.bouncycastle.asn1.iana \
        com.distrimind.bouncycastle.asn1.icao \
        com.distrimind.bouncycastle.asn1.misc \
        com.distrimind.bouncycastle.asn1.mozilla \
        com.distrimind.bouncycastle.asn1.nist \
        com.distrimind.bouncycastle.asn1.ocsp \
        com.distrimind.bouncycastle.asn1.oiw \
        com.distrimind.bouncycastle.asn1.pkcs \
        com.distrimind.bouncycastle.asn1.sec \
        com.distrimind.bouncycastle.asn1.smime \
        com.distrimind.bouncycastle.asn1.teletrust \
        com.distrimind.bouncycastle.asn1.test \
        com.distrimind.bouncycastle.asn1.tsp \
        com.distrimind.bouncycastle.asn1.util \
        com.distrimind.bouncycastle.asn1.x509 \
        com.distrimind.bouncycastle.asn1.x9 \
        com.distrimind.bouncycastle.math.ec \
        com.distrimind.bouncycastle.crypto \
        com.distrimind.bouncycastle.crypto.agreement \
        com.distrimind.bouncycastle.crypto.commitments \
        com.distrimind.bouncycastle.crypto.digests \
        com.distrimind.bouncycastle.crypto.encodings \
        com.distrimind.bouncycastle.crypto.ec \
        com.distrimind.bouncycastle.crypto.engines \
        com.distrimind.bouncycastle.crypto.generators \
        com.distrimind.bouncycastle.crypto.io \
        com.distrimind.bouncycastle.crypto.kems \
        com.distrimind.bouncycastle.crypto.macs \
        com.distrimind.bouncycastle.crypto.modes \
        com.distrimind.bouncycastle.crypto.paddings \
        com.distrimind.bouncycastle.crypto.params \
        com.distrimind.bouncycastle.crypto.signers \
        com.distrimind.bouncycastle.crypto.test \
        com.distrimind.bouncycastle.crypto.tls \
        com.distrimind.bouncycastle.crypto.examples \
        com.distrimind.bouncycastle.jce \
        com.distrimind.bouncycastle.jce.cert \
        com.distrimind.bouncycastle.jce.interfaces \
        com.distrimind.bouncycastle.jce.spec \
        com.distrimind.bouncycastle.jce.examples \
        com.distrimind.bouncycastle.jce.provider \
        com.distrimind.bouncycastle.jcajce.provider.asymmetric \
        com.distrimind.bouncycastle.jcajce.provider.asymmetric.ec \
        com.distrimind.bouncycastle.jcajce.provider.symmetric \
        com.distrimind.bouncycastle.jce.provider.test \
        com.distrimind.bouncycastle.ocsp \
        com.distrimind.bouncycastle.ocsp.test \
        com.distrimind.bouncycastle.x509 \
        com.distrimind.bouncycastle.x509.examples \
        com.distrimind.bouncycastle.x509.extension \
        com.distrimind.bouncycastle.util.encoders \
        com.distrimind.bouncycastle.util.test) > /dev/null \

    PATH=$JDK12PATH/bin:$PATH
    export PATH

    echo "compiling"

    (cd src/javax/crypto; javac -d ../../../classes -classpath ../../../classes:../../../src *.java */*.java)
    (cd src/java/security/spec; javac -d ../../../../classes -classpath ../../../../classes *.java )

    (cd src/com/distrimind/bouncycastle/jce/cert; javac -d ../../../../../classes -classpath ../../../../../classes:../../../../../src *.java  )
    (cd src/com/distrimind/bouncycastle/jcajce/provider; javac -d ../../../../../classes -classpath ../../../../../classes:../../../../../src a*/*.java )
    (cd src/com/distrimind/bouncycastle/jcajce/provider; javac -d ../../../../../classes -classpath ../../../../../classes:../../../../../src [cis]*/*.java )
    (cd src/com/distrimind/bouncycastle/jcajce/provider; javac -d ../../../../../classes -classpath ../../../../../classes:../../../../../src [abcis]*/*/*.java )
    (cd src/com/distrimind/bouncycastle; javac -d ../../../classes -classpath ../../../classes:../../../src *.java a*/*.java a*/*/*.java a*/*/*/*.java internal/*/*/*.java )
    (cd src/com/distrimind/bouncycastle; javac -d ../../../classes -classpath ../../../classes:../../../src [bc]*/*.java [bc]*/*/*.java [bc]*/*/*/*.java )
    (cd src/com/distrimind/bouncycastle; javac -d ../../../classes -classpath ../../../classes:../../../src [j]*/*.java [j]*/*/*.java [j]*/*/*/*.java [j]*/*/*/*/*.java)
    (cd src/com/distrimind/bouncycastle; javac -d ../../../classes -classpath ../../../classes:../../../src [mop]*/*.java [mop]*/*/*.java [mop]*/*/*/*.java [mop]*/*/*/*/*.java)
    (cd src/com/distrimind/bouncycastle; javac -d ../../../classes -classpath ../../../classes:../../../src [tu]*/*.java [tu]*/*/*.java [tu]*/*/*/*.java)
    (cd src/com/distrimind/bouncycastle; javac -d ../../../classes -classpath ../../../classes:../../../src [x]*/*/*.java)
    (cd src/com/distrimind/bouncycastle; javac -d ../../../classes -classpath ../../../classes:../../../src [x]*/*.java)



    echo "provider regression test"
    java -classpath classes com.distrimind.bouncycastle.jce.provider.test.RegressionTest

    (cd classes; jar cf ../../bctest-jdk12-$base.jar com/distrimind/bouncycastle/asn1/test com/distrimind/bouncycastle/crypto/test com/distrimind/bouncycastle/jce/provider/test)

    rm -rf classes/com/distrimind/bouncycastle/jce/provider/test

    (cd classes; jar cf ../../bcprov-jdk12-$base.jar java org)
    (cd classes; jar cf ../../jce-jdk12-$base.jar java javax org)
    )

    ( 2>&1 find $artifacts/jce-jdk12-$base -name CVS -exec rm -rf \{\} \;) > /dev/null
fi

if test "$base" != "" -a ! -d $artifacts/bcpkix-jdk12-$base
then
    echo "making PKIX release"

    mkdir $artifacts/bcpkix-jdk12-$base
    mkdir $artifacts/bcpkix-jdk12-$base/src
    tar cf - index.html LICENSE.html CONTRIBUTORS.html docs | (cd $artifacts/bcpkix-jdk12-$base; tar xf -)
    ((cd $jdk12src && tar cf - com/distrimind/bouncycastle/cert com/distrimind/bouncycastle/cms com/distrimind/bouncycastle/pkcs com/distrimind/bouncycastle/pkix com/distrimind/bouncycastle/openssl com/distrimind/bouncycastle/operator com/distrimind/bouncycastle/mozilla com/distrimind/bouncycastle/tsp com/distrimind/bouncycastle/voms ) | (cd $artifacts/bcpkix-jdk12-$base/src && tar xf -))
    (
    cd $artifacts/bcpkix-jdk12-$base; mkdir classes; mkdir javadoc;

    PATH=$JDK12PATH/bin:$PATH
    export PATH

    rm -rf src/com/distrimind/bouncycastle/cert/jcajce/JcaAttributeCertificateIssuer.java
    rm -rf src/com/distrimind/bouncycastle/cert/test/ConverterTest*
    rm -rf src/com/distrimind/bouncycastle/cert/test/CertPathLoopTest.java
    rm -rf src/com/distrimind/bouncycastle/cert/test/Bc*
    rm -rf src/com/distrimind/bouncycastle/cms/test
    rm -rf src/com/distrimind/bouncycastle/dvcs/test
    rm -rf src/com/distrimind/bouncycastle/eac/test
    rm -rf src/com/distrimind/bouncycastle/pkcs/test
    rm -rf src/com/distrimind/bouncycastle/tsp/test
    rm -rf src/com/distrimind/bouncycastle/est
    rm -rf src/com/distrimind/bouncycastle/tsp/GenTimeAccuracyUnit*
    rm -rf src/com/distrimind/bouncycastle/tsp/TimeStampTokenInfoUnit*
    rm src/com/distrimind/bouncycastle/cert/dane/fetcher/JndiDANEFetcherFactory.java
    find src -name AllTests.java -exec rm {} \;

    javadoc -windowtitle "$WINDOWTITLE" -doctitle "$DOCTITLE" \
        -header "$HEADER" \
        -group "Basic Signing And Encryption" "com.distrimind.bouncycastle.operator*" \
        -group "Certificate Generation And Handling Support Packages" "com.distrimind.bouncycastle.cert*" \
        -group "CMS Support Packages" "com.distrimind.bouncycastle.cms*" \
        -group "EAC Support Packages" "com.distrimind.bouncycastle.eac*" \
        -group "TSP Support Packages" "com.distrimind.bouncycastle.tsp*" \
        -group "PKCS Support Packages" "com.distrimind.bouncycastle.pkcs*" \
        -group "OpenSSL PEM Support Packages" "com.distrimind.bouncycastle.openssl*" \
        -classpath classes:../jce-jdk12-$base.jar \
        -d javadoc -sourcepath src \
        com.distrimind.bouncycastle.openssl \
        com.distrimind.bouncycastle.voms \
        com.distrimind.bouncycastle.mozilla \
        com.distrimind.bouncycastle.pkcs \
        com.distrimind.bouncycastle.pkcs.bc \
        com.distrimind.bouncycastle.pkcs.jcajce \
        com.distrimind.bouncycastle.cert \
        com.distrimind.bouncycastle.cert.cmp \
        com.distrimind.bouncycastle.cert.crmf \
        com.distrimind.bouncycastle.cert.jcajce \
        com.distrimind.bouncycastle.cert.ocsp \
        com.distrimind.bouncycastle.cert.selector \
        com.distrimind.bouncycastle.cms \
        com.distrimind.bouncycastle.cms.bc \
        com.distrimind.bouncycastle.cms.jcajce \
        com.distrimind.bouncycastle.cert.test > /dev/null \

    echo "compiling"

    (cd src/com/distrimind/bouncycastle; javac -d ../../../classes -classpath ../../../classes:../../../src:../../../../jce-jdk12-$base/classes */*.java */*/*.java */*/*/*.java)
    cat > classes/pg.mf <<%
Manifest-Version: 1.0
Extension-Name: com.distrimind.bouncycastle.bcpkix
Specification-Vendor: BouncyCastle.org
Specification-Version: 1.1
Implementation-Vendor-Id: com.distrimind.bouncycastle
Implementation-Vendor: BouncyCastle.org
Implementation-Version: $version.0
%

    (cd classes; jar cmf pg.mf ../../bcpkix-jdk12-$base.jar org)
    java -classpath ../jce-jdk12-$base.jar:classes com.distrimind.bouncycastle.cert.test.CertTest
    java -classpath ../jce-jdk12-$base.jar:classes com.distrimind.bouncycastle.cert.test.AttrCertTest
    java -classpath ../jce-jdk12-$base.jar:classes com.distrimind.bouncycastle.cert.test.PKCS10Test
    java -classpath ../jce-jdk12-$base.jar:classes com.distrimind.bouncycastle.cert.test.X509ExtensionUtilsTest
    )

    (2>&1 find $artifacts/bcpkix-jdk12-$base -name CVS -exec rm -rf \{\} \;) > /dev/null
fi

if test "$base" != "" -a ! -d $artifacts/bcpg-jdk12-$base
then
    echo "making OpenPGP release"

    mkdir $artifacts/bcpg-jdk12-$base
    mkdir $artifacts/bcpg-jdk12-$base/src
    tar cf - index.html LICENSE.html CONTRIBUTORS.html docs | (cd $artifacts/bcpg-jdk12-$base; tar xf -)
    ((cd $jdk12src && tar cf - com/distrimind/bouncycastle/apache com/distrimind/bouncycastle/openpgp com/distrimind/bouncycastle/bcpg com/distrimind/bouncycastle/gpg) |  (cd $artifacts/bcpg-jdk12-$base/src && tar xf -))
    (
    cd $artifacts/bcpg-jdk12-$base; mkdir classes; mkdir javadoc;

    PATH=$JDK12PATH/bin:$PATH
    export PATH

    rm -rf src/java
    rm -rf src/com/distrimind/bouncycastle/jce
    rm -rf src/com/distrimind/bouncycastle/ocsp
    rm -rf src/com/distrimind/bouncycastle/mail
    rm -rf src/com/distrimind/bouncycastle/pkcs
    rm -rf src/com/distrimind/bouncycastle/cms
    rm -rf src/com/distrimind/bouncycastle/mime
    rm -rf src/com/distrimind/bouncycastle/eac
    rm -rf src/com/distrimind/bouncycastle/cert
    rm -rf src/com/distrimind/bouncycastle/tsp
    rm -rf src/com/distrimind/bouncycastle/x509
    rm -rf src/com/distrimind/bouncycastle/voms
    rm -rf src/com/distrimind/bouncycastle/sasn1
    rm -rf src/com/distrimind/bouncycastle/est
    rm -rf src/com/distrimind/bouncycastle/asn1/test
    rm -rf src/com/distrimind/bouncycastle/gpg/keybox
    rm -rf src/com/distrimind/bouncycastle/gpg/test
    rm -f src/com/distrimind/bouncycastle/openpgp/test/DSA2Test.java
    rm -f src/com/distrimind/bouncycastle/openpgp/test/PGPUnicodeTest.java
    rm -f src/com/distrimind/bouncycastle/openpgp/test/PGPKeyRingTest.java
    rm -f src/com/distrimind/bouncycastle/openpgp/test/BcPGPEd25519JcaKeyPairConversionTest.java
    find src -name AllTests.java -exec rm {} \;

    javadoc -windowtitle "$WINDOWTITLE" -doctitle "$DOCTITLE" \
        -header "$HEADER" \
        -group "BCPG Support Packages" "com.distrimind.bouncycastle.bcpg*" \
        -group "OpenPGP Packages" "com.distrimind.bouncycastle.openpgp*" \
        -classpath classes:../jce-jdk12-$base.jar \
        -d javadoc -sourcepath src \
        com.distrimind.bouncycastle.bcpg \
        com.distrimind.bouncycastle.bcpg.attr \
        com.distrimind.bouncycastle.bcpg.sig \
        com.distrimind.bouncycastle.openpgp \
        com.distrimind.bouncycastle.openpgp.examples \
        com.distrimind.bouncycastle.openpgp.test > /dev/null \

    echo "compiling"

    ed src/com/distrimind/bouncycastle/bcpg/ArmoredOutputStream.java <<%
/@RELEASE_NAME@/s//$version/
w
q
%

    ed src/com/distrimind/bouncycastle/openpgp/test/RegressionTest.java <<%
g/new PGPKeyRingTest(),/d
w
q
%

    (cd src/com/distrimind/bouncycastle; javac -d ../../../classes -classpath ../../../classes:../../../src:../../../../jce-jdk12-$base/classes */*.java */*/*.java)
    cat > classes/pg.mf <<%
Manifest-Version: 1.0
Extension-Name: com.distrimind.bouncycastle.bcpg
Specification-Vendor: BouncyCastle.org
Specification-Version: 1.1
Implementation-Vendor-Id: com.distrimind.bouncycastle
Implementation-Vendor: BouncyCastle.org
Implementation-Version: $version.0
%

    cp ../../../../pg/src/test/resources/com/distrimind/bouncycastle/openpgp/test/bigpub.asc classes/com/distrimind/bouncycastle/openpgp/test/bigpub.asc
    cp ../../../../pg/src/test/resources/com/distrimind/bouncycastle/openpgp/test/eddsa-sks-pub-keyring.asc classes/com/distrimind/bouncycastle/openpgp/test/eddsa-sks-pub-keyring.asc
    cp ../../../../pg/src/test/resources/com/distrimind/bouncycastle/openpgp/test/longSigSubPack.asc classes/com/distrimind/bouncycastle/openpgp/test/longSigSubPack.asc
    (dbase=`pwd`; cd ../../../../pg/src/test/resources/; tar cf - pgpdata | (cd $dbase/classes; tar xf -)) 
    

    (cd classes; jar cmf pg.mf ../../bcpg-jdk12-$base.jar org)
    java -classpath ../jce-jdk12-$base.jar:classes com.distrimind.bouncycastle.openpgp.test.RegressionTest

    )

    (2>&1 find $artifacts/bcpg-jdk12-$base -name CVS -exec rm -rf \{\} \;) > /dev/null
fi

